# Generated by Django 5.1.15 on 2026-01-19 23:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academics', '0003_alter_session_options_remove_session_end_year_and_more'),
        ('students', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='student',
            options={'ordering': ['roll_number']},
        ),
        migrations.CreateModel(
            name='StudentSubject',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('group', models.CharField(blank=True, choices=[('science', 'Science'), ('business', 'Business'), ('humanities', 'Humanities'), ('religion', 'Religion')], max_length=20, null=True)),
                ('enrollment_date', models.DateTimeField(auto_now_add=True)),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='student_subjects', to='students.student')),
                ('subject', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='student_enrollments', to='academics.subject')),
            ],
            options={
                'ordering': ['subject__name'],
                'unique_together': {('student', 'subject')},
            },
        ),
        migrations.AddField(
            model_name='student',
            name='subjects',
            field=models.ManyToManyField(related_name='students', through='students.StudentSubject', to='academics.subject'),
        ),
    ]
