# Generated by Django 5.1.15 on 2026-01-19 23:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0002_alter_student_options_studentsubject_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='student',
            name='subjects',
        ),
        migrations.DeleteModel(
            name='StudentSubject',
        ),
        migrations.AddField(
            model_name='student',
            name='group',
            field=models.CharField(blank=True, choices=[('science', 'Science'), ('business', 'Business'), ('humanities', 'Humanities'), ('religion', 'Religion')], max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='student',
            name='subjects',
            field=models.ManyToManyField(blank=True, related_name='student_enrollments', to='academics.subject'),
        ),
    ]
