# Generated by Django 5.1.15 on 2026-01-20 00:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0003_simplify_student_model'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='group',
            field=models.CharField(blank=True, choices=[('science', 'Science'), ('business', 'Business Studies'), ('humanities', 'Humanities')], max_length=20, null=True),
        ),
    ]
