# Generated by Django 5.1.15 on 2026-01-20 00:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academics', '0004_alter_subject_group'),
        ('exams', '0001_initial'),
        ('students', '0004_alter_student_group'),
    ]

    operations = [
        migrations.CreateModel(
            name='ExamMark',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('exam_name', models.CharField(choices=[('ct_exam', 'CT-Exam'), ('midterm', 'Mid-Term'), ('half_yearly', 'Half Yearly'), ('test', 'Test'), ('pretest', 'Pre-test'), ('year_final', 'Year Final')], max_length=20)),
                ('cq_marks', models.DecimalField(blank=True, decimal_places=2, help_text='Constructed Question marks', max_digits=5, null=True)),
                ('mct_marks', models.DecimalField(blank=True, decimal_places=2, help_text='Multiple Choice Test marks', max_digits=5, null=True)),
                ('lab_marks', models.DecimalField(blank=True, decimal_places=2, help_text='Laboratory marks', max_digits=5, null=True)),
                ('total_class', models.IntegerField(default=10, help_text='Total classes in the course')),
                ('present', models.IntegerField(default=0, help_text='Classes attended')),
                ('absent', models.IntegerField(default=0, help_text='Classes missed')),
                ('total_marks', models.DecimalField(blank=True, decimal_places=2, help_text='Total marks obtained', max_digits=5, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='exam_marks', to='academics.session')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='exam_marks', to='students.student')),
                ('subject', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='exam_marks', to='academics.subject')),
            ],
            options={
                'verbose_name': 'Exam Mark',
                'verbose_name_plural': 'Exam Marks',
                'ordering': ['student__roll_number', 'subject__name'],
                'unique_together': {('exam_name', 'student', 'subject', 'session')},
            },
        ),
    ]
