# Generated by Django 5.1.15 on 2026-01-20 01:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exams', '0002_exammark'),
    ]

    operations = [
        migrations.CreateModel(
            name='ExamType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Exam name (e.g., CT-Exam, Mid-Term, Half Yearly, Test, Pre-test, Year Final)', max_length=100, unique=True)),
                ('description', models.TextField(blank=True, help_text='Description of this exam type', null=True)),
                ('is_active', models.BooleanField(default=True, help_text='Enable/disable this exam type')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Exam Type',
                'verbose_name_plural': 'Exam Types',
                'ordering': ['name'],
            },
        ),
        migrations.AlterField(
            model_name='exam',
            name='exam_type',
            field=models.ForeignKey(help_text='Select exam type', on_delete=django.db.models.deletion.CASCADE, related_name='exams', to='exams.examtype'),
        ),
    ]
