# Generated by Django 5.1.15 on 2026-01-19 22:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academics', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='subject',
            options={'ordering': ['group', 'category', 'name']},
        ),
        migrations.AddField(
            model_name='subject',
            name='category',
            field=models.CharField(choices=[('compulsory', 'Compulsory Subjects'), ('group', 'Group Subjects'), ('optional', 'Optional / 4th Subjects')], default='compulsory', max_length=20),
        ),
        migrations.AddField(
            model_name='subject',
            name='group',
            field=models.CharField(choices=[('science', 'Science Group (বিজ্ঞান বিভাগ)'), ('business', 'Business Studies Group (ব্যবসায় শিক্ষা বিভাগ)'), ('humanities', 'Humanities Group (মানবিক বিভাগ)'), ('religion', 'Religion (ধর্ম)')], default='science', max_length=20),
        ),
        migrations.AlterField(
            model_name='subject',
            name='class_name',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='subjects', to='academics.class'),
        ),
    ]
