# Generated by Django 5.1.15 on 2026-01-19 23:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academics', '0002_alter_subject_options_subject_category_subject_group_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='session',
            options={'ordering': ['-name']},
        ),
        migrations.RemoveField(
            model_name='session',
            name='end_year',
        ),
        migrations.RemoveField(
            model_name='session',
            name='start_year',
        ),
        migrations.AlterField(
            model_name='session',
            name='name',
            field=models.CharField(help_text='Format: YYYY-YYYY (e.g., 2024-2025)', max_length=100, unique=True),
        ),
    ]
