# Generated by Django 5.1.15 on 2026-01-20 00:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academics', '0003_alter_session_options_remove_session_end_year_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subject',
            name='group',
            field=models.CharField(choices=[('science', 'Science'), ('business', 'Business Studies'), ('humanities', 'Humanities')], default='science', max_length=20),
        ),
    ]
